import { Crowd, crowdAgentParamsDefaults } from 'recast-navigation';

let crowd = null;
const agents = new Map(); // Maps agent index (id) to our custom agent data

/**
 * Initializes the Detour Crowd simulation.
 * @param {NavMesh} navMesh - The navmesh generated by recast.
 * @param {number} maxAgents - The maximum number of agents the crowd can manage.
 * @param {number} maxAgentRadius - The radius of the largest agent.
 */
export function initCrowd(navMesh, maxAgents, maxAgentRadius) {
    if (!navMesh) {
        console.error('CrowdManager: Cannot initialize without a navMesh.');
        return;
    }
    crowd = new Crowd(navMesh, maxAgents, maxAgentRadius);
    console.log('Detour Crowd initialized.');
}

/**
 * Adds a new agent to the crowd simulation.
 * @param {THREE.Vector3} position - The starting position of the agent.
 * @param {object} agentParams - Configuration for the agent.
 * @param {object} userData - Any custom data you want to associate (e.g., the Three.js model).
 * @returns {number | null} The agent's index (ID) or null if failed.
 */
// export function addAgent(position, agentParams, userData = {}) {
//     if (!crowd) {
//         console.error("Crowd manager is not initialized.");
//         return null;
//     }

//     const params = { ...crowdAgentParamsDefaults };
//     params.radius = agentParams.radius ?? 0.4;
//     params.height = agentParams.height ?? 1.8;
//     params.maxAcceleration = agentParams.maxAcceleration ?? 4.0;
//     params.maxSpeed = agentParams.maxSpeed ?? 1.5;
//     params.collisionQueryRange = params.radius * 8;
//     params.pathOptimizationRange = params.radius * 30;
//     params.updateFlags = 0; // Set standard behaviors
//     params.separationWeight = agentParams.separationWeight ?? 2.0;

//     const agentIndex = crowd.addAgent(position, params);

//     // This is the correct way to handle the failure: check the return value
//     if (agentIndex !== -1) {
//         agents.set(agentIndex, {
//             ...userData,
//             agent: crowd.getAgent(agentIndex),
//         });
//         console.log("AGENT INDEX: ", agentIndex);
//         console.log("AGENT: ", crowd.getAgent(agentIndex));
//         console.log(`Agent ${agentIndex} added to crowd at`, position);
//         return agentIndex;
//     } else {
//         // Log a more helpful error message
//         console.error("Failed to add agent to crowd. The position might be invalid or the crowd is full.");
//         return null;
//     }
// }

// src/game_logic/CrowdManager.js

export function addAgent(position, agentParams, userData = {}) {
    if (!crowd) {
        console.error("Crowd manager is not initialized.");
        return null;
    }

    const params = { ...crowdAgentParamsDefaults };
    params.radius = agentParams.radius ?? 0.4;
    params.height = agentParams.height ?? 1.8;
    params.maxAcceleration = agentParams.maxAcceleration ?? 4.0;
    params.maxSpeed = agentParams.maxSpeed ?? 1.5;
    params.collisionQueryRange = params.radius * 8;
    params.pathOptimizationRange = params.radius * 30;
    params.updateFlags = 0; 
    params.separationWeight = agentParams.separationWeight ?? 2.0;

    const agentIndex = crowd.addAgent(position, params);

    if (agentIndex !== -1) {
        agents.set(agentIndex, {
            ...userData,
            agent: crowd.getAgent(agentIndex),
        });
        console.log(`Agent ${agentIndex} added to crowd at`, position);
        return agentIndex;
    } else {
        // ✅ NEW: More detailed error log
        console.error(
            "Failed to add agent to crowd. The crowd might be full, or the provided position is invalid.",
            "\nFailed Position:", position
        );
        return null;
    }
}

/**
 * Sets the navigation target for a specific agent.
 * @param {number} agentId - The ID of the agent to command.
 * @param {THREE.Vector3} targetPosition - The world coordinate target.
 * @param {NavMeshQuery} navQuery - The query interface for the navmesh.
 */
export function setAgentTarget(agentId, targetPosition, navQuery) {
    if (!crowd || !navQuery || !agents.has(agentId)) return;

    const agent = agents.get(agentId).agent;
    const { point: navTarget } = navQuery.findClosestPoint(targetPosition);

    if (navTarget) {
        agent.requestMoveTarget(navTarget);
        console.log(`Agent ${agentId} target set to`, navTarget);
    }
}

/**
 * Updates the crowd simulation.
 * @param {number} delta - The frame delta time.
 */
export function updateCrowd(delta) {
    if (!crowd) return;
    crowd.update(delta);
}

/**
 * Gets the current state of all agents.
 * @returns {Map<number, object>} A map of agents with their current simulation state.
 */
export function getAgents() {
    return agents;
}